package com.hvhn.backend.model.enums;

public enum NotificationType {
    REQUEST_CREATED_NEARBY,
    REQUEST_ACCEPTED,
    REQUEST_PROGRESS_UPDATED,
    REQUEST_COMPLETION_REQUESTED,
    REQUEST_COMPLETION_CONFIRMED,
    REQUEST_COMPLETION_REJECTED,
    REQUEST_CANCELLED,
    REQUEST_COMMENT_ADDED,
    COMMUNITY_JOIN_APPROVED,
    COMMUNITY_JOIN_REJECTED,
    COMMUNITY_ROLE_CHANGED,
    COMMUNITY_MEMBER_REMOVED,
    COMMUNITY_ANNOUNCEMENT_CREATED,
    QUESTION_ANSWERED,
    QUESTION_ANSWER_ACCEPTED,
    QUESTION_UPVOTED,
    ANSWER_UPVOTED,
    CAMPAIGN_CREATED,
    CAMPAIGN_CONTRIBUTION_ADDED,
    CAMPAIGN_STATUS_CHANGED,
    CHAT_MESSAGE_RECEIVED,
    CHAT_REACTION_ADDED,
    SYSTEM_ALERT,
    SECURITY_ALERT
}
