const RECENT_DATES = [
  '2026-04-12T08:15:00.000Z',
  '2026-04-12T07:40:00.000Z',
  '2026-04-12T06:10:00.000Z',
  '2026-04-11T18:25:00.000Z',
  '2026-04-11T16:45:00.000Z',
  '2026-04-11T14:05:00.000Z',
  '2026-04-10T12:20:00.000Z',
  '2026-04-10T09:00:00.000Z',
  '2026-04-09T17:55:00.000Z',
  '2026-04-09T13:35:00.000Z',
  '2026-04-08T11:45:00.000Z',
  '2026-04-08T08:05:00.000Z',
];

export const MOCK_ADMIN_STATS = {
  totalRequestsToday: 12,
  activeVolunteers: 8,
  pendingRequests: 5,
  resolvedRequests: 24,
  totalMembers: 150,
};

export const MOCK_ADMIN_REQUESTS = [
  {
    id: 'REQ-1048',
    title: 'B positive donor needed by afternoon',
    category: 'BLOOD',
    urgency: 'HIGH',
    status: 'PENDING',
    raisedBy: 'Priya Patel',
    requesterEmail: 'priya@example.com',
    location: 'AIIMS Delhi, Ward 3',
    communityId: 'community-aiims',
    communityName: 'AIIMS Delhi',
    description: 'One donor is needed for a surgery scheduled later today. Patient family is already on-site.',
    createdAt: RECENT_DATES[0],
  },
  {
    id: 'REQ-1047',
    title: 'Medicine drop for senior citizen',
    category: 'MEDICAL',
    urgency: 'MEDIUM',
    status: 'ACTIVE',
    raisedBy: 'Amit Kumar',
    requesterEmail: 'amit@example.com',
    location: 'Green Valley Society, Tower B',
    communityId: 'community-green-valley',
    communityName: 'Green Valley Society',
    description: 'Insulin refill needs to reach an elderly resident before noon.',
    createdAt: RECENT_DATES[1],
  },
  {
    id: 'REQ-1046',
    title: 'Lunch packets for flood-affected lane',
    category: 'FOOD',
    urgency: 'HIGH',
    status: 'ACTIVE',
    raisedBy: 'Sana Khan',
    requesterEmail: 'sana.khan@gvs.com',
    location: 'Noida Sector 62 Relief Camp',
    communityId: 'community-green-valley',
    communityName: 'Green Valley Society',
    description: 'Need food packets for around 18 people displaced by overnight flooding.',
    createdAt: RECENT_DATES[2],
  },
  {
    id: 'REQ-1045',
    title: 'Volunteer support for registration desk',
    category: 'GENERAL',
    urgency: 'LOW',
    status: 'RESOLVED',
    raisedBy: 'Rahul Sharma',
    requesterEmail: 'rahul@example.com',
    location: 'IIT Delhi, Main Hall',
    communityId: 'community-iit-delhi',
    communityName: 'IIT Delhi',
    description: 'Two volunteers helped coordinate medical camp registration.',
    createdAt: RECENT_DATES[3],
  },
  {
    id: 'REQ-1044',
    title: 'Wheelchair transport assistance',
    category: 'MEDICAL',
    urgency: 'MEDIUM',
    status: 'PENDING',
    raisedBy: 'Kavya Bansal',
    requesterEmail: 'kavya.bansal@aiims.edu',
    location: 'South Extension to AIIMS',
    communityId: 'community-aiims',
    communityName: 'AIIMS Delhi',
    description: 'Family needs help shifting a patient from cab to OPD entrance tomorrow morning.',
    createdAt: RECENT_DATES[4],
  },
  {
    id: 'REQ-1043',
    title: 'Breakfast support for patient attendants',
    category: 'FOOD',
    urgency: 'LOW',
    status: 'RESOLVED',
    raisedBy: 'Neha Arora',
    requesterEmail: 'neha.arora@gvs.com',
    location: 'AIIMS Waiting Area',
    communityId: 'community-aiims',
    communityName: 'AIIMS Delhi',
    description: 'Request completed with support from three volunteers.',
    createdAt: RECENT_DATES[5],
  },
  {
    id: 'REQ-1042',
    title: 'Community notice help for blood camp',
    category: 'GENERAL',
    urgency: 'LOW',
    status: 'ACTIVE',
    raisedBy: 'Sneha Gupta',
    requesterEmail: 'sneha@example.com',
    location: 'IIT Delhi Campus',
    communityId: 'community-iit-delhi',
    communityName: 'IIT Delhi',
    description: 'Need volunteers to distribute notices and guide participants.',
    createdAt: RECENT_DATES[6],
  },
  {
    id: 'REQ-1041',
    title: 'O negative donor verification follow-up',
    category: 'BLOOD',
    urgency: 'HIGH',
    status: 'RESOLVED',
    raisedBy: 'Dr. Raghav Menon',
    requesterEmail: 'raghav.menon@aiims.edu',
    location: 'AIIMS Emergency',
    communityId: 'community-aiims',
    communityName: 'AIIMS Delhi',
    description: 'Donor matched and arrived in time. Request closed successfully.',
    createdAt: RECENT_DATES[7],
  },
  {
    id: 'REQ-1040',
    title: 'Evening meal delivery for isolation ward',
    category: 'FOOD',
    urgency: 'MEDIUM',
    status: 'PENDING',
    raisedBy: 'Farhan Ali',
    requesterEmail: 'farhan.ali@alumni.iitd.ac.in',
    location: 'Safdarjung Enclave',
    communityId: 'community-iit-delhi',
    communityName: 'IIT Delhi',
    description: 'Need packaged meals and contactless drop support.',
    createdAt: RECENT_DATES[8],
  },
  {
    id: 'REQ-1039',
    title: 'Medical file pickup from diagnostics center',
    category: 'MEDICAL',
    urgency: 'LOW',
    status: 'RESOLVED',
    raisedBy: 'Abhishek Jain',
    requesterEmail: 'abhishek.jain@gvs.com',
    location: 'Sector 18, Noida',
    communityId: 'community-green-valley',
    communityName: 'Green Valley Society',
    description: 'Volunteer completed report collection and delivery.',
    createdAt: RECENT_DATES[9],
  },
  {
    id: 'REQ-1038',
    title: 'Community pantry restock',
    category: 'GENERAL',
    urgency: 'MEDIUM',
    status: 'ACTIVE',
    raisedBy: 'Vikram Singh',
    requesterEmail: 'vikram@example.com',
    location: 'Rohini Community Hub',
    communityId: 'community-rohini-care',
    communityName: 'Rohini Care Circle',
    description: 'Need help restocking pantry essentials before weekend distribution.',
    createdAt: RECENT_DATES[10],
  },
  {
    id: 'REQ-1037',
    title: 'Food support for hostel student in recovery',
    category: 'FOOD',
    urgency: 'LOW',
    status: 'PENDING',
    raisedBy: 'Aarti Mehra',
    requesterEmail: 'aarti.mehra@iitd.ac.in',
    location: 'IIT Delhi Hostel 6',
    communityId: 'community-iit-delhi',
    communityName: 'IIT Delhi',
    description: 'Need volunteers to coordinate meals for three days.',
    createdAt: RECENT_DATES[11],
  },
];

export const MOCK_ADMIN_USERS = [
  {
    id: 'user-1',
    fullName: 'Rahul Sharma',
    email: 'rahul@example.com',
    role: 'VOLUNTEER',
    communityId: 'community-iit-delhi',
    community: 'IIT Delhi',
    verified: true,
    blocked: false,
    badge: 'Helper',
    requestsHelped: 19,
    joinedDate: '2026-01-14T10:00:00.000Z',
  },
  {
    id: 'user-2',
    fullName: 'Priya Patel',
    email: 'priya@example.com',
    role: 'VOLUNTEER',
    communityId: 'community-aiims',
    community: 'AIIMS Delhi',
    verified: true,
    blocked: false,
    badge: 'Champion',
    requestsHelped: 31,
    joinedDate: '2026-01-09T09:30:00.000Z',
  },
  {
    id: 'user-3',
    fullName: 'Amit Kumar',
    email: 'amit@example.com',
    role: 'USER',
    communityId: 'community-green-valley',
    community: 'Green Valley Society',
    verified: true,
    blocked: false,
    badge: 'Volunteer',
    requestsHelped: 7,
    joinedDate: '2026-02-01T08:20:00.000Z',
  },
  {
    id: 'user-4',
    fullName: 'Sneha Gupta',
    email: 'sneha@example.com',
    role: 'VOLUNTEER',
    communityId: 'community-iit-delhi',
    community: 'IIT Delhi',
    verified: true,
    blocked: false,
    badge: 'Champion',
    requestsHelped: 24,
    joinedDate: '2026-01-22T12:10:00.000Z',
  },
  {
    id: 'user-5',
    fullName: 'Vikram Singh',
    email: 'vikram@example.com',
    role: 'VOLUNTEER',
    communityId: 'community-rohini-care',
    community: 'Rohini Care Circle',
    verified: true,
    blocked: false,
    badge: 'Hero',
    requestsHelped: 36,
    joinedDate: '2025-12-18T07:45:00.000Z',
  },
  {
    id: 'user-6',
    fullName: 'Admin User',
    email: 'admin@hvhn.com',
    role: 'ADMIN',
    communityId: 'community-iit-delhi',
    community: 'HVHN Platform',
    verified: true,
    blocked: false,
    badge: 'Hero',
    requestsHelped: 0,
    joinedDate: '2025-11-01T10:45:00.000Z',
  },
  {
    id: 'user-7',
    fullName: 'Neha Arora',
    email: 'neha.arora@gvs.com',
    role: 'USER',
    communityId: 'community-green-valley',
    community: 'Green Valley Society',
    verified: true,
    blocked: false,
    badge: 'Helper',
    requestsHelped: 11,
    joinedDate: '2026-02-12T11:00:00.000Z',
  },
  {
    id: 'user-8',
    fullName: 'Ritesh Sood',
    email: 'ritesh.sood@rohini.org',
    role: 'USER',
    communityId: 'community-rohini-care',
    community: 'Rohini Care Circle',
    verified: false,
    blocked: false,
    badge: 'Newcomer',
    requestsHelped: 1,
    joinedDate: '2026-03-18T09:00:00.000Z',
  },
  {
    id: 'user-9',
    fullName: 'Kavya Bansal',
    email: 'kavya.bansal@aiims.edu',
    role: 'VOLUNTEER',
    communityId: 'community-aiims',
    community: 'AIIMS Delhi',
    verified: true,
    blocked: false,
    badge: 'Helper',
    requestsHelped: 14,
    joinedDate: '2026-02-26T08:30:00.000Z',
  },
  {
    id: 'user-10',
    fullName: 'Suraj Nair',
    email: 'suraj.nair@example.com',
    role: 'USER',
    communityId: 'community-aiims',
    community: 'AIIMS Delhi',
    verified: false,
    blocked: true,
    badge: 'Newcomer',
    requestsHelped: 0,
    joinedDate: '2026-03-04T14:15:00.000Z',
  },
  {
    id: 'user-11',
    fullName: 'Farhan Ali',
    email: 'farhan.ali@alumni.iitd.ac.in',
    role: 'VOLUNTEER',
    communityId: 'community-iit-delhi',
    community: 'IIT Delhi',
    verified: true,
    blocked: false,
    badge: 'Volunteer',
    requestsHelped: 10,
    joinedDate: '2026-01-28T06:40:00.000Z',
  },
  {
    id: 'user-12',
    fullName: 'Mitali Verma',
    email: 'mitali.verma@gvs.com',
    role: 'USER',
    communityId: 'community-green-valley',
    community: 'Green Valley Society',
    verified: true,
    blocked: false,
    badge: 'Helper',
    requestsHelped: 5,
    joinedDate: '2026-02-17T16:00:00.000Z',
  },
];

export const MOCK_ADMIN_COMMUNITIES = [
  {
    id: 'community-iit-delhi',
    name: 'IIT Delhi',
    type: 'College',
    memberCount: 124,
    requestCount: 43,
    status: 'ACTIVE',
    address: 'Hauz Khas, New Delhi',
    description: 'Student and alumni support network for campus and nearby neighborhoods.',
  },
  {
    id: 'community-aiims',
    name: 'AIIMS Delhi',
    type: 'Hospital',
    memberCount: 171,
    requestCount: 58,
    status: 'ACTIVE',
    address: 'Ansari Nagar, New Delhi',
    description: 'Verified medical help network for patients, attendants, and volunteers.',
  },
  {
    id: 'community-green-valley',
    name: 'Green Valley Society',
    type: 'Society',
    memberCount: 89,
    requestCount: 31,
    status: 'PENDING',
    address: 'Sector 62, Noida',
    description: 'Residential support network focused on elders, families, and local emergencies.',
  },
  {
    id: 'community-rohini-care',
    name: 'Rohini Care Circle',
    type: 'Society',
    memberCount: 67,
    requestCount: 19,
    status: 'ACTIVE',
    address: 'Rohini, Delhi',
    description: 'Neighborhood volunteer circle coordinating essentials, food, and follow-up care.',
  },
];

export const MOCK_BROADCAST_HISTORY = [
  {
    id: 'broadcast-1',
    message: 'High urgency medical requests should be acknowledged within 10 minutes today.',
    targetType: 'ALL',
    targetLabel: 'All Communities',
    sentBy: 'Admin User',
    sentAt: '2026-04-11T09:00:00.000Z',
  },
  {
    id: 'broadcast-2',
    message: 'Green Valley admin team: please verify the pending member queue before tonight.',
    targetType: 'SPECIFIC',
    communityId: 'community-green-valley',
    targetLabel: 'Green Valley Society',
    sentBy: 'Admin User',
    sentAt: '2026-04-10T14:30:00.000Z',
  },
  {
    id: 'broadcast-3',
    message: 'Reminder: update volunteer badges after weekend response reviews.',
    targetType: 'ALL',
    targetLabel: 'All Communities',
    sentBy: 'Admin User',
    sentAt: '2026-04-09T18:10:00.000Z',
  },
];

export const MOCK_NOTIFICATION_PREFERENCES = {
  emailAlertsHighUrgency: true,
  dailySummaryEmail: false,
};

export const MOCK_ADMIN_ANALYTICS = {
  requestsPerDay: [
    { day: 'Sun', requests: 7 },
    { day: 'Mon', requests: 11 },
    { day: 'Tue', requests: 15 },
    { day: 'Wed', requests: 9 },
    { day: 'Thu', requests: 18 },
    { day: 'Fri', requests: 13 },
    { day: 'Sat', requests: 10 },
  ],
  categoryBreakdown: [
    { name: 'Blood', value: 30, color: '#ef4444' },
    { name: 'Medical', value: 25, color: '#3b82f6' },
    { name: 'Food', value: 25, color: '#22c55e' },
    { name: 'General', value: 20, color: '#9ca3af' },
  ],
  averageResponseTime: '11m 24s',
  topVolunteers: [
    { id: 'vol-1', name: 'Vikram Singh', helpedCount: 36, badge: 'Hero' },
    { id: 'vol-2', name: 'Priya Patel', helpedCount: 31, badge: 'Champion' },
    { id: 'vol-3', name: 'Sneha Gupta', helpedCount: 24, badge: 'Champion' },
    { id: 'vol-4', name: 'Rahul Sharma', helpedCount: 19, badge: 'Helper' },
    { id: 'vol-5', name: 'Kavya Bansal', helpedCount: 14, badge: 'Helper' },
  ],
};

export function cloneAdminMockData(value) {
  return JSON.parse(JSON.stringify(value));
}
